### ISSUE TITLE
Contributors tab is not loaded by default

### ISSUE THREAD

**Issue by eliseealex** [gitskarios/Gitskarios#126] opened 2015-05-22 10:47 UTC
On Nexus 5, Android 5.1, Contributors tab in any project is not loaded by default. Am I the one who has this problem?

**Comment by alorma** [comment] 2015-05-22 11:01
Hi @eliseealex no, you are not the only one :(

I will check that in the next release, thanks for the feedback

**Comment by eliseealex** [comment] 2015-05-22 19:48
Thanks for your attention. I like your application and i will try to help you with some more issues and may be pull requests if i would have enough knowledge.

**Comment by alorma** [comment] 2015-05-22 19:53
All kind of support is welcome :)

**Comment by arkadiytehgraet** [comment] 2015-07-17 19:52
What's the status of the issue? I can't reproduce it

**Comment by alorma** [comment] 2015-07-17 20:20
I think is fixed now.

I will release in next version

**Comment by arkadiytehgraet** [comment] 2015-07-17 20:21
Cool, thanks :)

**Closed** 2015-07-23 20:27 UTC
Labels: bug
