### ISSUE TITLE
unable to edit after post 

### ISSUE THREAD

**Issue by GeorgeWL** [gitskarios/Gitskarios#575] opened 2016-09-14 19:30 UTC
https://github.com/ccrama/Slide/issues/2160<br /><br />https://streamable.com/xq21

**Comment by alorma** [comment] 2016-09-14 19:31
? please, explain the problem

**Comment by GeorgeWL** [comment] 2016-09-14 21:03
when I attempt to edit a comment on an issue,  the edit doesn't show as being made in the interface. 

And it doesn't propagate to the web version either.

**Comment by MelvynEzi** [comment] 2016-09-14 22:45
I can confirm. I had to use the browser on desktop version to edit the comment.

**Comment by MelvynEzi** [comment] 2016-09-20 11:43
@alorma this is a functionality breaking issue. editing a freshly posted comment will not change the comment, sometimes even stating that its not ready.

**Comment by alorma** [comment] 2016-09-20 11:48
Test comment

**Comment by alorma** [comment] 2016-09-20 11:49
Mmm, i've updated an issue comment (comment above), and it changed on the web

**Comment by MelvynEzi** [comment] 2016-09-20 12:15
Test edited 1

**Comment by MelvynEzi** [comment] 2016-09-20 12:16
Test edited 2

**Comment by MelvynEzi** [comment] 2016-09-20 12:16
Hmm.. seems like when having a bad connection causes the changes to be lost when attempting to edit.

**Comment by MelvynEzi** [comment] 2016-09-22 06:16
Somehow, some comments (in another pull request of another repo) would only show a toast "Not ready"

**Comment by GeorgeWL** [comment] 2016-09-28 08:31
Could it be something as simple as the API being slow to respond occasionally?

**Comment by MelvynEzi** [comment] 2016-09-28 09:17
"Not ready" toast shows even after 1 week.

**Comment by GeorgeWL** [comment] 2016-10-03 09:47
I just had a new one.  edit causes app crash, I guess it's a new issue.

**Comment by GeorgeWL** [comment] 2016-10-04 12:56
#584

**Comment by webmaster33** [comment] 2016-10-18 17:20
I also had crash, when tapping the edit icon.

**Comment by alorma** [comment] 2016-10-18 17:22
Fixed

**Comment by ghost** [comment] 2016-10-18 17:22
Nope for me.

**Comment by alorma** [comment] 2016-10-18 17:32
I not deployed it to production yet....

**Comment by MelvynEzi** [comment] 2016-10-18 21:16
Edit: solved stacktrace

**Comment by alorma** [comment] 2016-10-19 00:35
O_o, well, it's other crash

**Comment by webmaster33** [comment] 2016-10-22 11:10
Test message. Edited.

**Comment by webmaster33** [comment] 2016-10-22 11:12
Now comment editing works for me, doesn't crash. The only issue is, that issue is not refreshing automatically, after edit was submitted. 
Version 4.4.8.
Hmmm. Now refreshed automatically after editing.

**Comment by MelvynEzi** [comment] 2016-10-22 12:12
You'll have issues editing comments on PRs and issues in repos that you don't own (other than this).

**Comment by webmaster33** [comment] 2016-10-22 13:07
This is not my issue, but still does not crash, when editing. Also I don't see edit icon on other comments, just mine.

**Comment by alorma** [comment] 2016-10-23 13:40
So, can i close the issue?

**Comment by webmaster33** [comment] 2016-11-05 16:28
This seems to work in last version. Edited.

**Closed as completed** 2016-11-05 16:33 UTC
