### ISSUE TITLE
crash on attempt to look at comment.

### ISSUE THREAD

**Issue by meepingsnesroms** [gitskarios/Gitskarios#588] opened 2016-10-06 00:30 UTC
Build version: 4.4.4 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-05 17:27:58 
Device: Motorola Moto E 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String core.User.getLogin()' on a null object reference
    at core.repositories.Repo.toInfo(Repo.java:333)
    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:380)
    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:60)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.lambda$populate$233(EventViewHolder.java:39)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.access$lambda$0(EventViewHolder.java)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder$$Lambda$1.onClick(Unknown Source)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21158)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by GeorgeWL** [comment] 2016-10-12 22:11
Closed as this appears to be a duplicate of #584

**Closed as completed by GeorgeWL** 2016-10-12 22:11 UTC
