### ISSUE TITLE
Crash when attempting to edit comment.

### ISSUE THREAD

**Issue by xChitose** [gitskarios/Gitskarios#591] opened 2016-10-09 15:01 UTC
Build version: 4.4.4 <br />Build date: 1979-11-30 00:00:00 <br />Current date: 2016-10-09 10:59:51 <br />Device: LGE LGLS992 <br /><br />Stack trace:  <br />java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.ContentEditorActivity}: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment<br />  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)<br /> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)<br />  at android.app.ActivityThread.access$900(ActivityThread.java:157)<br /> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)<br />   at android.os.Handler.dispatchMessage(Handler.java:102)<br />   at android.os.Looper.loop(Looper.java:148)<br />    at android.app.ActivityThread.main(ActivityThread.java:5551)<br />  at java.lang.reflect.Method.invoke(Native Method)<br /> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)<br />    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)<br />Caused by: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.GithubComment<br />  at com.alorma.github.sdk.bean.issue.IssueStoryComment.<init>(IssueStoryComment.java:50)<br />   at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:57)<br />   at com.alorma.github.sdk.bean.issue.IssueStoryComment$1.createFromParcel(IssueStoryComment.java:54)<br />   at android.os.Parcel.readParcelable(Parcel.java:2367)<br /> at android.os.Parcel.readValue(Parcel.java:2264)<br />  at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)<br />   at android.os.BaseBundle.unparcel(BaseBundle.java:221)<br />    at android.os.BaseBundle.getString(BaseBundle.java:920)<br />   at com.alorma.github.ui.activity.ContentEditorActivity.onCreate(ContentEditorActivity.java:133)<br />   at android.app.Activity.performCreate(Activity.java:6272)<br /> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)<br />    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)<br /> ... 9 more

**Comment by GeorgeWL** [comment] 2016-10-12 22:11
Closed as this appears to be a duplicate of #588

**Closed as completed by GeorgeWL** 2016-10-12 22:11 UTC
